namespace Core.Entities
{
    public class CustomerBasket
    {
        /// <summary>
        /// For Redis
        /// </summary>
        public CustomerBasket()
        {
        }

        public CustomerBasket(string id)
        {
            Id = id;
        }

        /// <summary>
        /// Unique id for each customer, generated by Angular
        /// </summary>
        public string Id { get; set; }

        public List<BasketItem> Items { get; set; } = new List<BasketItem>();
    }
}